# Generated by Django 3.2.5 on 2021-07-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
